// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { TopNavigation } from "../components/TopNavigation";
import { SideNavigation } from "../components/SideNavigation";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import AuthGuard from "../components/auth/AuthGuard";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    const session = await auth();

    return (
        <SessionProvider session={session}>
            {/* 头部导航栏 */}
            <header className="fixed top-0 left-0 right-0 z-50 bg-white p-4 border border-gray-200">
                <TopNavigation />
            </header>

            {/* 侧边导航栏 */}
            <SideNavigation />

            {/* 页面内容 */}
            <main className={`${geistSans.variable} ${geistMono.variable} antialiased ml-16 mt-16 transition-all   duration-300`}>
                <AuthGuard>
                    {children}
                </AuthGuard>
            </main>
        </SessionProvider>
    );
}
